global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "aether-mailer-server"
    static_configs:
      - targets: ["host.docker.internal:9464"]
    scrape_interval: 5s
    metrics_path: "/metrics"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "aether-mailer-frontend"
    static_configs:
      - targets: ["host.docker.internal:3000"]
    metrics_path: "/api/metrics"
    scrape_interval: 10s

  - job_name: "postgres"
    static_configs:
      - targets: ["host.docker.internal:5432"]
    scrape_interval: 30s
